/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
      RouterView: typeof import('vue-router')['RouterView']
      ElButton: typeof import('element-plus/es')['ElButton']
      ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
      ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
      ElIcon: typeof import('element-plus/es')['ElIcon']
      ElInput: typeof import('element-plus/es')['ElInput']
      ElMenu: typeof import('element-plus/es')['ElMenu']
      ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
      ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
      ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
      ElTag: typeof import('element-plus/es')['ElTag']
  }
}
